---
- hosts: all
  become: true
  vars_files:
  - ansible/vars/all.yml

  handlers:
  - name: restart mysql
    service: name=mysql enabled=yes state=restarted

  tasks:

  - name: download nodejs
    shell:  curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
  
  - name: install the nginx rpm from a remote repo
    yum:
      name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
      state: present

  - name: install mysql from remote repo
    yum:
      name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
      state: present


  - name: Install a list of packages
    yum:
      name:
        - epel-release
        - yum-utils 
        - device-mapper-persistent-data 
        - lvm2
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - nodejs
        - git
        - maven
        - nginx
        - openssl
        - vim
        #- mysql-community-server.x86_64 
        - mysql-server
        - MySQL-python
      state: present
  
  - name: install angular
    shell: npm install -g @angular/cli
  
  - name: add docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install docker 
    yum:
      name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present

  #nginx ssl 

  - name: install pip
    yum:
      name: python-pip
      state: present

  - name: nginx as a service
    shell: systemctl enable nginx

  - name: install pip
    shell: pip install pyopenssl

  - name: Create directory
    file:
      path: /etc/ssl/private
      state: directory
      mode: 0755

  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /etc/ssl/private/developer.px.pem
 
  - name: Create directory
    file:
      path: /etc/ssl/csr
      state: directory
      mode: 0755
 
  - name: Generate an OpenSSL Certificate Signing Request
    openssl_csr:
      path: /etc/ssl/csr/www.developer.px.csr
      privatekey_path: /etc/ssl/private/developer.px.pem
      country_name: IN
      organization_name: jiro
      email_address: jiro@developer.px
      common_name: www.developer.px
  
  - name: Generate a self signed certificate
    openssl_certificate:
      path: /etc/ssl/certs/nginx-selfsigned.crt
      privatekey_path: /etc/ssl/private/developer.px.pem
      csr_path: /etc/ssl/csr/www.developer.px.csr
      provider: selfsigned

  - name: copy app file to host
    copy:
      src: nginx/dev.conf
      dest: /etc/nginx/conf.d/dev.conf
      owner: root
      group: root
      mode: 0644

  - name: start nginx
    shell: systemctl start nginx

  - name: More Configure the timezone
    become: yes
    file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

  - name: Set default system language pack
    shell: localectl set-locale LANG={{server.locale}}
    become: yes

  - name: install htop
    yum:
      name: htop
      state: present

  - name: copy my.cnf
    template:
      src: ansible/templates/my.cnf.j2
      dest: /etc/my.cnf
      mode: 0644
    notify: restart mysql

  - name: get root password
    shell: "grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log | awk -F ' ' '{print $(NF)}'"
    register: root_password

  - name: update expired root user password
    command: mysql --user root --password={{ root_password.stdout }} --connect-expired-password --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root_password }}';"

  - name: create mysql client user
    mysql_user:
      login_user: root
      login_password: "{{ mysql.root_password }}"
      name: "{{ mysql.user }}"
      password: "{{ mysql.password }}"
      priv: '*.*:ALL,GRANT'
      state: present
      host: '%'